# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[(b'new', b'New'), (b'act', b'Active'), (b'pau', b'Paused'), (b'arc', b'Archived')], default=b'new', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_for', to='flows.Flow'),
        ),
    ]
