# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[(b'cat', b'Categorization'), (b'att', b'Attributes')], max_length=3)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('operation', models.CharField(choices=[(b'eq', b'Equals'), (b'eqi', b'Equals Integer'), (b'th', b'Less Than'), (b'the', b'Less Than Equals'), (b'gt', b'Greater Than'), (b'gte', b'Greater Than Equals'), (b'mrx', b'Matches regex')], max_length=3)),
                ('value', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='flows.Flow')),
                ('next_flow', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flows.Flow')),
            ],
        ),
    ]
