# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_flow_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='next_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flows.Flow'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='operation',
            field=models.CharField(choices=[(b'in', b'In'), (b'eq', b'Equals'), (b'eqi', b'Equals Integer'), (b'th', b'Less Than'), (b'the', b'Less Than Equals'), (b'gt', b'Greater Than'), (b'gte', b'Greater Than Equals'), (b'mrx', b'Matches regex')], max_length=3),
        ),
    ]
